name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compiles
      id: compiles
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compiles
        setup-command: make
        command: make test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILES_RESULTS: "${{steps.compiles.outputs.result}}"
      with:
        runners: compiles
